Lesson 3: Готовое ДЗ
Ruzhelovich-Vladimir/xanadu_shop pull request #3
Opened 2020-12-12 18:46 UTC by Ruzhelovich-Vladimir

Прошу проверить

2020-12-12 19:18 UTC, Vokler requested changes

2020-12-12 19:18 UTC, Vokler commented on generate_fixture
> +#./manage.py dumpdata mainapp.Brand > mainapp/fixtures/Brand.json
Если это считается как инструкция, то лучше вынести в README
Вот инструкция по оформлению
https://github.com/GnuriaN/format-README

2020-12-12 19:18 UTC, Vokler commented on load_fixture
> +./manage.py loaddata Brand
То же самое, что описал выше для generate_fixture

2020-12-12 19:18 UTC, Vokler commented on mainapp/models.py
> +    volume = models.DecimalField(
В FK лучше еще использовать null=True вместе с blank=True
https://djbook.ru/rel1.9/ref/models/fields.html

2020-12-12 19:18 UTC, Vokler commented on mainapp/views.py
По pep8 лучше использовать абсолютный импорт, то есть from `mainapp.models import ...`
https://www.python.org/dev/peps/pep-0008/#imports

2020-12-12 19:18 UTC, Vokler commented on mainapp/views.py
> +    products = Product.objects.all()[start-1:finish-1]
Это что-то типо пагинации?
Лучше тогда так https://docs.djangoproject.com/en/3.1/topics/pagination/

2020-12-12 19:21 UTC, Ruzhelovich-Vladimir commented on generate_fixture
> +#./manage.py dumpdata mainapp.Brand > mainapp/fixtures/Brand.json
нет, это bash скрипт

2020-12-14 11:01 UTC, Vokler approved these changes

2020-12-14 11:01 UTC, merged